"""
Plan Adherence Metric Demonstration

This script demonstrates the Plan Adherence metric using a planning agent.
The metric evaluates whether the agent follows the plan it created during
task execution, comparing planned steps against actual execution.

Key Concepts:
- Trace-based metric using @observe decorator
- Extracts plan from agent's reasoning/output
- Compares planned steps with executed actions
- Evaluates order compliance and completeness

Reference: https://deepeval.com/docs/metrics-plan-adherence
"""

from deepeval.tracing import observe, update_current_trace
from deepeval.dataset import Golden, EvaluationDataset
from deepeval.metrics import PlanAdherenceMetric
from deepeval.test_case import ToolCall
from deepeval.models.llms import LocalModel
from settings import ProjectSettings

# Initialize settings and model
settings = ProjectSettings()

model = LocalModel(
    model=settings.llm_model,
    api_key=settings.llm_api_key,
    base_url=settings.llm_base_url,
    temperature=settings.llm_temperature,
)


# =============================================================================
# Simulated Tools
# =============================================================================


def search_web(query: str) -> dict:
    """Search the web for information."""
    return {"results": [f"Result for: {query}"], "count": 5}


def analyze_data(data: dict) -> dict:
    """Analyze data and extract insights."""
    return {"insights": ["Key finding 1", "Key finding 2"], "confidence": 0.85}


def generate_report(insights: list) -> str:
    """Generate a report from insights."""
    return f"Report based on {len(insights)} insights"


def validate_sources(sources: list) -> dict:
    """Validate the credibility of sources."""
    return {"valid": True, "score": 0.9}


def format_output(content: str) -> str:
    """Format content for presentation."""
    return f"Formatted: {content}"


def cross_reference(data: dict) -> dict:
    """Cross-reference data with other sources."""
    return {"verified": True, "matches": 3}


# =============================================================================
# Agent Implementations - Different Adherence Levels
# =============================================================================


@observe
def perfect_adherence_agent(user_input: str) -> str:
    """
    PERFECT ADHERENCE - Agent follows its plan exactly.
    Expected: HIGH adherence score (1.0)
    """
    tools_called = []

    # The agent's explicit plan (would normally be generated by LLM)
    plan = """
    My plan to complete this research task:
    1. Search the web for relevant information
    2. Analyze the collected data
    3. Generate a comprehensive report
    """

    # Execute Step 1: Search (as planned)
    search_results = search_web("AI trends 2024")
    tools_called.append(
        ToolCall(
            name="SearchWeb",
            description="Search the web for information",
            input_parameters={"query": "AI trends 2024"},
        )
    )

    # Execute Step 2: Analyze (as planned)
    analysis = analyze_data(search_results)
    tools_called.append(
        ToolCall(
            name="AnalyzeData",
            description="Analyze data and extract insights",
            input_parameters={"data": search_results},
        )
    )

    # Execute Step 3: Generate report (as planned)
    report = generate_report(analysis["insights"])
    tools_called.append(
        ToolCall(
            name="GenerateReport",
            description="Generate a report from insights",
            input_parameters={"insights": analysis["insights"]},
        )
    )

    output = f"""
    {plan}
    
    Execution completed following the plan:
    - Step 1: Searched for AI trends 2024 ✓
    - Step 2: Analyzed {len(search_results['results'])} results ✓
    - Step 3: Generated report ✓
    
    Final Report: {report}
    """

    update_current_trace(input=user_input, output=output, tools_called=tools_called)

    return output


@observe
def partial_adherence_agent(user_input: str) -> str:
    """
    PARTIAL ADHERENCE - Agent skips some planned steps.
    Expected: MEDIUM adherence score (0.5-0.7)
    """
    tools_called = []

    # The agent's explicit plan
    plan = """
    My plan to complete this research task:
    1. Search the web for relevant information
    2. Validate sources for credibility
    3. Analyze the collected data
    4. Generate a comprehensive report
    """

    # Execute Step 1: Search (as planned)
    search_results = search_web("AI trends 2024")
    tools_called.append(
        ToolCall(
            name="SearchWeb",
            description="Search the web for information",
            input_parameters={"query": "AI trends 2024"},
        )
    )

    # SKIP Step 2: Validation (not executed!)

    # Execute Step 3: Analyze (as planned, but out of sequence now)
    analysis = analyze_data(search_results)
    tools_called.append(
        ToolCall(
            name="AnalyzeData",
            description="Analyze data and extract insights",
            input_parameters={"data": search_results},
        )
    )

    # Execute Step 4: Generate report (as planned)
    report = generate_report(analysis["insights"])
    tools_called.append(
        ToolCall(
            name="GenerateReport",
            description="Generate a report from insights",
            input_parameters={"insights": analysis["insights"]},
        )
    )

    output = f"""
    {plan}
    
    Execution (with deviations):
    - Step 1: Searched for AI trends 2024 ✓
    - Step 2: Validate sources ✗ (SKIPPED)
    - Step 3: Analyzed results ✓
    - Step 4: Generated report ✓
    
    Note: Skipped validation step due to time constraints.
    
    Final Report: {report}
    """

    update_current_trace(input=user_input, output=output, tools_called=tools_called)

    return output


@observe
def order_deviation_agent(user_input: str) -> str:
    """
    ORDER DEVIATION - Agent executes steps out of planned order.
    Expected: MEDIUM adherence score (0.4-0.6)
    """
    tools_called = []

    # The agent's explicit plan
    plan = """
    My plan to complete this research task:
    1. Search the web for relevant information
    2. Analyze the collected data  
    3. Validate sources for credibility
    4. Generate a comprehensive report
    """

    # Execute Step 1: Search (as planned)
    search_results = search_web("AI trends 2024")
    tools_called.append(
        ToolCall(
            name="SearchWeb",
            description="Search the web for information",
            input_parameters={"query": "AI trends 2024"},
        )
    )

    # Execute Step 3 BEFORE Step 2 (out of order!)
    validation = validate_sources(search_results["results"])
    tools_called.append(
        ToolCall(
            name="ValidateSources",
            description="Validate source credibility",
            input_parameters={"sources": search_results["results"]},
        )
    )

    # Now execute Step 2 (out of order!)
    analysis = analyze_data(search_results)
    tools_called.append(
        ToolCall(
            name="AnalyzeData",
            description="Analyze data and extract insights",
            input_parameters={"data": search_results},
        )
    )

    # Execute Step 4: Generate report (as planned)
    report = generate_report(analysis["insights"])
    tools_called.append(
        ToolCall(
            name="GenerateReport",
            description="Generate a report from insights",
            input_parameters={"insights": analysis["insights"]},
        )
    )

    output = f"""
    {plan}
    
    Execution (with order changes):
    - Step 1: Search ✓
    - Step 3: Validate ✓ (executed before analysis)
    - Step 2: Analyze ✓ (executed after validation)
    - Step 4: Report ✓
    
    Note: Reordered steps for efficiency.
    
    Final Report: {report}
    """

    update_current_trace(input=user_input, output=output, tools_called=tools_called)

    return output


@observe
def extra_steps_agent(user_input: str) -> str:
    """
    EXTRA STEPS - Agent adds unplanned steps during execution.
    Expected: MEDIUM-HIGH adherence score (0.6-0.8)
    """
    tools_called = []

    # The agent's explicit plan
    plan = """
    My plan to complete this research task:
    1. Search the web for relevant information
    2. Analyze the collected data
    3. Generate a comprehensive report
    """

    # Execute Step 1: Search (as planned)
    search_results = search_web("AI trends 2024")
    tools_called.append(
        ToolCall(
            name="SearchWeb",
            description="Search the web for information",
            input_parameters={"query": "AI trends 2024"},
        )
    )

    # EXTRA: Validate sources (not in plan!)
    validation = validate_sources(search_results["results"])
    tools_called.append(
        ToolCall(
            name="ValidateSources",
            description="Validate source credibility",
            input_parameters={"sources": search_results["results"]},
        )
    )

    # Execute Step 2: Analyze (as planned)
    analysis = analyze_data(search_results)
    tools_called.append(
        ToolCall(
            name="AnalyzeData",
            description="Analyze data and extract insights",
            input={"data": search_results},
        )
    )

    # EXTRA: Cross-reference (not in plan!)
    cross_ref = cross_reference(analysis)
    tools_called.append(
        ToolCall(
            name="CrossReference",
            description="Cross-reference data with other sources",
            input_parameters={"data": analysis},
        )
    )

    # Execute Step 3: Generate report (as planned)
    report = generate_report(analysis["insights"])
    tools_called.append(
        ToolCall(
            name="GenerateReport",
            description="Generate a report from insights",
            input_parameters={"insights": analysis["insights"]},
        )
    )

    output = f"""
    {plan}
    
    Execution (with additions):
    - Step 1: Search ✓
    - ADDED: Validate sources (for quality)
    - Step 2: Analyze ✓
    - ADDED: Cross-reference (for verification)
    - Step 3: Report ✓
    
    Note: Added validation and cross-referencing for quality.
    
    Final Report: {report}
    """

    update_current_trace(input=user_input, output=output, tools_called=tools_called)

    return output


@observe
def no_adherence_agent(user_input: str) -> str:
    """
    NO ADHERENCE - Agent completely ignores its plan.
    Expected: LOW adherence score (0.0-0.2)
    """
    tools_called = []

    # The agent's explicit plan
    plan = """
    My plan to complete this research task:
    1. Search the web for relevant information
    2. Analyze the collected data
    3. Generate a comprehensive report
    """

    # Execute completely different steps!

    # Do format output (not in plan)
    formatted = format_output("some content")
    tools_called.append(
        ToolCall(
            name="FormatOutput",
            description="Format content for presentation",
            input_parameters={"content": "some content"},
        )
    )

    # Do cross-reference (not in plan)
    cross_ref = cross_reference({"data": "test"})
    tools_called.append(
        ToolCall(
            name="CrossReference",
            description="Cross-reference data",
            input_parameters={"data": {"data": "test"}},
        )
    )

    output = f"""
    {plan}
    
    Execution (completely different!):
    - Formatted output
    - Cross-referenced data
    
    Note: Deviated from plan entirely.
    
    Result: {formatted}
    """

    update_current_trace(input=user_input, output=output, tools_called=tools_called)

    return output


# =============================================================================
# Evaluation Functions
# =============================================================================


def evaluate_adherence_scenarios():
    """Evaluate all adherence scenarios."""
    print("\n" + "=" * 70)
    print("PLAN ADHERENCE METRIC DEMONSTRATION")
    print("=" * 70)

    metric = PlanAdherenceMetric(
        model=model,
        threshold=0.7,
        include_reason=True,
        verbose_mode=True,
    )

    user_input = "Research and summarize the latest AI trends for 2024"

    agents = [
        ("Perfect Adherence (follows plan exactly)", perfect_adherence_agent),
        ("Partial Adherence (skips some steps)", partial_adherence_agent),
        ("Order Deviation (wrong step order)", order_deviation_agent),
        ("Extra Steps (adds unplanned steps)", extra_steps_agent),
        ("No Adherence (ignores plan)", no_adherence_agent),
    ]

    results = []

    for name, agent_func in agents:
        print(f"\n{'='*60}")
        print(f"SCENARIO: {name}")
        print(f"{'='*60}")

        dataset = EvaluationDataset(goldens=[Golden(input=user_input)])

        for golden in dataset.evals_iterator(metrics=[metric]):
            output = agent_func(golden.input)

            # Show abbreviated output
            print(f"\nUser Input: {golden.input}")
            print(f"\nAgent Plan + Execution (abbreviated):")
            print(output[:500] + "...")

            print(f"\n--- Adherence Evaluation ---")
            print(f"Score: {metric.score:.2f}")
            print(f"Passed: {metric.score >= metric.threshold}")
            print(f"Reason: {metric.reason}")

            results.append((name, metric.score))

    return results


def explain_adherence_scenarios():
    """Explain the different adherence scenarios."""
    print("\n" + "=" * 70)
    print("UNDERSTANDING PLAN ADHERENCE SCENARIOS")
    print("=" * 70)

    print(
        """
    Plan Adherence measures how well an agent follows its stated plan.
    Here's what each scenario demonstrates:
    
    ┌─────────────────────────────────────────────────────────────────┐
    │ PERFECT ADHERENCE (Score: ~1.0)                                 │
    ├─────────────────────────────────────────────────────────────────┤
    │ Plan:      1. Search → 2. Analyze → 3. Report                  │
    │ Execution: 1. Search → 2. Analyze → 3. Report                  │
    │ Result:    All steps executed in exact order                    │
    └─────────────────────────────────────────────────────────────────┘
    
    ┌─────────────────────────────────────────────────────────────────┐
    │ PARTIAL ADHERENCE (Score: ~0.5-0.7)                            │
    ├─────────────────────────────────────────────────────────────────┤
    │ Plan:      1. Search → 2. Validate → 3. Analyze → 4. Report    │
    │ Execution: 1. Search → (skip) → 3. Analyze → 4. Report         │
    │ Result:    Missing Step 2 (Validate)                            │
    └─────────────────────────────────────────────────────────────────┘
    
    ┌─────────────────────────────────────────────────────────────────┐
    │ ORDER DEVIATION (Score: ~0.4-0.6)                              │
    ├─────────────────────────────────────────────────────────────────┤
    │ Plan:      1. Search → 2. Analyze → 3. Validate → 4. Report    │
    │ Execution: 1. Search → 3. Validate → 2. Analyze → 4. Report    │
    │ Result:    Steps 2 and 3 swapped                                │
    └─────────────────────────────────────────────────────────────────┘
    
    ┌─────────────────────────────────────────────────────────────────┐
    │ EXTRA STEPS (Score: ~0.6-0.8)                                  │
    ├─────────────────────────────────────────────────────────────────┤
    │ Plan:      1. Search → 2. Analyze → 3. Report                  │
    │ Execution: 1. Search → [Validate] → 2. Analyze → [CrossRef]    │
    │            → 3. Report                                          │
    │ Result:    Planned steps done + extra unplanned steps           │
    └─────────────────────────────────────────────────────────────────┘
    
    ┌─────────────────────────────────────────────────────────────────┐
    │ NO ADHERENCE (Score: ~0.0-0.2)                                 │
    ├─────────────────────────────────────────────────────────────────┤
    │ Plan:      1. Search → 2. Analyze → 3. Report                  │
    │ Execution: Format → CrossReference                              │
    │ Result:    Completely different execution from plan             │
    └─────────────────────────────────────────────────────────────────┘
    """
    )


# =============================================================================
# Main Entry Point
# =============================================================================


def main():
    """Run all demonstrations."""
    print("=" * 70)
    print("PLAN ADHERENCE METRIC DEMONSTRATION")
    print("Planning Agent with Different Adherence Levels")
    print("=" * 70)

    print(
        """
    The Plan Adherence metric evaluates whether an agent follows
    the plan it creates. This is crucial for:
    
    - Predictability: Agents should do what they say they'll do
    - Debugging: Identify when/why agents deviate from plans
    - Trust: Users rely on agents behaving consistently
    - Quality: Ensure planning logic is actually used
    
    This demo shows five adherence scenarios from perfect to none.
    """
    )

    # Explain scenarios
    explain_adherence_scenarios()

    # Run evaluations
    results = evaluate_adherence_scenarios()

    # Summary
    print("\n" + "=" * 70)
    print("RESULTS SUMMARY")
    print("=" * 70)

    for name, score in results:
        status = "PASS" if score >= 0.7 else "FAIL"
        bar = "█" * int(score * 20) + "░" * (20 - int(score * 20))
        print(f"\n{name}")
        print(f"  [{bar}] {score:.2f} [{status}]")

    print("\n" + "=" * 70)
    print("KEY TAKEAWAYS")
    print("=" * 70)
    print(
        """
    1. Plan Adherence is a TRACE-BASED metric (requires @observe)
    2. The agent must generate an EXPLICIT plan for evaluation
    3. Score considers both COMPLETENESS and ORDER of steps
    4. Skipped steps reduce score significantly
    5. Extra steps may reduce score (depending on context)
    6. Order changes are penalized but less than skipped steps
    
    Best Practices for High Adherence:
    - Make plans explicit in agent output/reasoning
    - Execute steps in the order they're planned
    - If deviating, update the plan before executing
    - Use chain-of-thought to make planning visible
    
    When Low Adherence is Acceptable:
    - Error recovery (adding retry steps)
    - Adaptive planning (updating based on results)
    - Safety additions (adding validation steps)
    """
    )


if __name__ == "__main__":
    main()
